-- 建立权限ACTION表
CREATE TABLE "SYSTEM"."FARMLAND_TABLE_ACTION" 
 (	"ID" NUMBER NOT NULL ENABLE, 
	"ACTION_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	 CONSTRAINT "FARMLAND_ACTION_PK" PRIMARY KEY ("ID")
 );
-- 建立一个ACTION Sequence序列
CREATE SEQUENCE FARMLAND_SEQUENCE_ACTION
 INCREMENT BY 1   -- 每次加几个  
     START WITH 1     -- 从1开始计数  
     NOMAXVALUE       -- 不设置最大值  
     NOCYCLE ;         -- 一直累加，不循环
-- 建立一个ACTION触发器
CREATE TRIGGER  FARMLAND_TRIGGER_ACTION BEFORE
insert ON FARMLAND_TABLE_ACTION FOR EACH ROW
begin
select FARMLAND_SEQUENCE_ACTION.nextval into:New.ID from dual;
end;


-- 权限组表ACTION_GROUP
CREATE TABLE "SYSTEM"."FARMLAND_TABLE_ACTION_GROUP" 
  (	"ID" NUMBER NOT NULL ENABLE, 
	"GROUP_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	 CONSTRAINT "FARMLAND_ACTION_GROUP_PK" PRIMARY KEY ("ID")
  );
-- 建立一个ACTION_GROUP Sequence序列
CREATE SEQUENCE FARMLAND_SEQUENCE_ACTION_GROUP
 INCREMENT BY 1   -- 每次加几个  
     START WITH 1     -- 从1开始计数  
     NOMAXVALUE       -- 不设置最大值  
     NOCYCLE ;         -- 一直累加，不循环
-- 建立一个ACTION_GROUP触发器
CREATE TRIGGER  FARMLAND_TRIGGER_ACTION_GROUP BEFORE
insert ON FARMLAND_TABLE_ACTION_GROUP FOR EACH ROW
begin
select FARMLAND_SEQUENCE_ACTION_GROUP.nextval into:New.ID from dual;
end;


-- 建立一个用户表
CREATE TABLE "SYSTEM"."FARMLAND_TABLE_USER" 
("ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"MOBILE_PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"TELPHONE_NUMBER" VARCHAR2(20 BYTE), 
	 CONSTRAINT "TABLE_FARMLAND_USER_PK" PRIMARY KEY ("ID")
) ;
-- 建立一个用户 Sequence序列
CREATE SEQUENCE FARMLAND_SEQUENCE_USER
 INCREMENT BY 1   -- 每次加几个  
     START WITH 1     -- 从1开始计数  
     NOMAXVALUE       -- 不设置最大值  
     NOCYCLE ;         -- 一直累加，不循环
-- 建立一个用户触发器
CREATE TRIGGER  FARMLAND_TRIGGER_USER BEFORE
insert ON FARMLAND_TABLE_USER FOR EACH ROW
begin
select FARMLAND_SEQUENCE_USER.nextval into:New.ID from dual;
end;


-- 删除权限和权限组对照
drop sequence "SYSTEM"."FARMLAND_SEQUENCE_AG"
drop trigger "SYSTEM"."FARMLAND_TRIGGER_AG"
drop table "SYSTEM"."FARMLAND_TABLE_AG" 
-- 建立一个权限和权限组对照表
CREATE TABLE "SYSTEM"."FARMLAND_TABLE_AG" 
("ID" NUMBER NOT NULL ENABLE, 
	"ACTION_ID" NUMBER NOT NULL ENABLE, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FARMLAND_TABLE_AG_PK" PRIMARY KEY ("ID")
) ;
-- 建立一个用户 Sequence序列
CREATE SEQUENCE FARMLAND_SEQUENCE_AG
 INCREMENT BY 1   -- 每次加几个  
     START WITH 1     -- 从1开始计数  
     NOMAXVALUE       -- 不设置最大值  
     NOCYCLE ;         -- 一直累加，不循环
-- 建立一个用户触发器
CREATE TRIGGER  FARMLAND_TRIGGER_AG BEFORE
insert ON FARMLAND_TABLE_AG FOR EACH ROW
begin
select FARMLAND_SEQUENCE_AG.nextval into:New.ID from dual;
end;


-- 建立一个用户权限组对照表
CREATE TABLE "SYSTEM"."FARMLAND_TABLE_UG" 
("ID" NUMBER NOT NULL ENABLE, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FARMLAND_TABLE_UG_PK" PRIMARY KEY ("ID")
) ;
--
CREATE SEQUENCE FARMLAND_SEQUENCE_UG
 INCREMENT BY 1   -- 每次加几个  
     START WITH 1     -- 从1开始计数  
     NOMAXVALUE       -- 不设置最大值  
     NOCYCLE ;         -- 一直累加，不循环
--
CREATE TRIGGER  FARMLAND_TRIGGER_UG BEFORE
insert ON FARMLAND_TABLE_UG FOR EACH ROW
begin
select FARMLAND_SEQUENCE_UG.nextval into:New.ID from dual;
end;